"""Add plan column to projects

Revision ID: cb922c2a0181
Revises: 89d8db4feb3f
Create Date: 2026-03-08 18:35:51.860444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb922c2a0181'
down_revision: Union[str, Sequence[str], None] = '89d8db4feb3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('plan', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'plan')
    # ### end Alembic commands ###
