"""remove_unique_title

Revision ID: cc97d99019d2
Revises: cb922c2a0181
Create Date: 2026-03-08 20:52:14.776471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc97d99019d2'
down_revision: Union[str, Sequence[str], None] = 'cb922c2a0181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=1)
    # ### end Alembic commands ###
